databases:
  - name: the_chef
    plan: free
    databaseName: the_chef
    user: the_chef_user

services:
  - type: web
    plan: free
    name: the_chef
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn the_chef.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: the_chef
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4